name: vuegouette
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  redis:
    image: redis
    restart: always
    environment:
      - REDIS_PASSWORD=redis
    ports:
      - "6379:6379"

  app:
    image: fadilmuh22/vuegouette:latest
    volumes:
      - .env:/app/.env
    environment:
      PORT: 1323
      DB_URL: postgres://postgres:postgres@postgres:5432/postgres
      JWT_SECRET: a1b2c3d4e5f6g7h8i9j0
      REDIS_HOST: redis
      REDIS_PASSWORD: redis
      REDIS_DB: 0
    ports:
      - "80:1323"
    depends_on:
       - postgres
       - redis

